package oopuasc2301010270;

import static oopuasc2301010270.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;



/**
 *
 * @author Ari Widya
 * TGL : 28 Juni 2025
 */
public class fPeminjaman extends javax.swing.JFrame {
    DefaultTableModel DTM = new DefaultTableModel();

    /**
     * Creates new form fPeminjaman
     * @throws java.sql.SQLException
     */
    public fPeminjaman() throws SQLException {
        initComponents();
        
        
        datePINJAM.setDateFormatString("yyyy-MM-dd");
        dateKEMBALI.setDateFormatString("yyyy-MM-dd");
        
        tblpeminjaman_buku.setModel(DTM);
        DTM.addColumn("ID");
        DTM.addColumn("NIM");
        DTM.addColumn("Nama");
        DTM.addColumn("Kode Buku");
        DTM.addColumn("Judul Buku");
        DTM.addColumn("Tanggal Pinjam");
        DTM.addColumn("Tanggal Kembali");
        
        //untuk atur layout tabel
        tblpeminjaman_buku.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblpeminjaman_buku.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblpeminjaman_buku.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblpeminjaman_buku.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblpeminjaman_buku.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblpeminjaman_buku.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblpeminjaman_buku.getColumnModel().getColumn(6).setPreferredWidth(100);
        
        lsdtpeminjaman();
        clearform();
        tombol(false);
        cTAMBAH.setEnabled(true);
        cKELUAR.setEnabled(true);
        fieldAktif(false);
    }
   
    private void tombol(boolean opsi){
        cTAMBAH.setEnabled(opsi);
        cUBAH.setEnabled(opsi);
        cHAPUS.setEnabled(opsi);
        cKELUAR.setEnabled(opsi);
    }
    private void fieldAktif(boolean opsi){
        txNIM.setEditable(opsi);
        txNAMA.setEditable(opsi);
        txKODE.setEditable(opsi);
        txJUDUL.setEditable(opsi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblpeminjaman_buku = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txJUMLAHPEMINJAMAN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txJUDUL = new javax.swing.JTextField();
        cUBAH = new javax.swing.JButton();
        txKODE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cTAMBAH = new javax.swing.JButton();
        dateKEMBALI = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txNIM = new javax.swing.JTextField();
        cKELUAR = new javax.swing.JButton();
        datePINJAM = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cHAPUS = new javax.swing.JButton();
        txNAMA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(320, -10));

        tblpeminjaman_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblpeminjaman_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpeminjaman_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpeminjaman_buku);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Jumlah Peminjaman :");

        txJUMLAHPEMINJAMAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJUMLAHPEMINJAMANActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 35)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Data Peminjaman Buku");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Form Data Peminjaman Buku");

        cUBAH.setText("Ubah");
        cUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUBAHActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama Mahasiswa");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal Kembali");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Judul Buku");

        cTAMBAH.setText("Tambah");
        cTAMBAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cTAMBAHMouseClicked(evt);
            }
        });
        cTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTAMBAHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NIM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kode Buku");

        txNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIMActionPerformed(evt);
            }
        });

        cKELUAR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cKELUAR.setText("Keluar");
        cKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKELUARActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Pinjam");

        cHAPUS.setText("Hapus");
        cHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHAPUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txJUDUL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txKODE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cTAMBAH)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cUBAH)
                            .addGap(12, 12, 12)
                            .addComponent(cHAPUS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cKELUAR))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(datePINJAM, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateKEMBALI, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(463, 463, 463))
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txJUMLAHPEMINJAMAN, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txJUMLAHPEMINJAMAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txKODE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txJUDUL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateKEMBALI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePINJAM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cKELUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txJUMLAHPEMINJAMANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJUMLAHPEMINJAMANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJUMLAHPEMINJAMANActionPerformed

    private void tblpeminjaman_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpeminjaman_bukuMouseClicked
    txNIM.setText(tblpeminjaman_buku.getValueAt(tblpeminjaman_buku.getSelectedRow(), 1).toString());
    txNAMA.setText(tblpeminjaman_buku.getValueAt(tblpeminjaman_buku.getSelectedRow(), 2).toString());
    txKODE.setText(tblpeminjaman_buku.getValueAt(tblpeminjaman_buku.getSelectedRow(), 3).toString());
    txJUDUL.setText(tblpeminjaman_buku.getValueAt(tblpeminjaman_buku.getSelectedRow(), 4).toString());
    
    try {
        java.util.Date tglPinjam = new SimpleDateFormat("yyyy-MM-dd").parse(tblpeminjaman_buku.getValueAt(tblpeminjaman_buku.getSelectedRow(), 5).toString());
        datePINJAM.setDate(tglPinjam);

        java.util.Date tglKembali = new SimpleDateFormat("yyyy-MM-dd").parse(tblpeminjaman_buku.getValueAt(tblpeminjaman_buku.getSelectedRow(), 6).toString());
        dateKEMBALI.setDate(tglKembali);
    } catch (Exception e) {
        e.printStackTrace(); // untuk debug kalau ada kesalahan parsing tanggal
    }
    
    cUBAH.setEnabled(true);
    cHAPUS.setEnabled(true);
    
    fieldAktif(false);
    }//GEN-LAST:event_tblpeminjaman_bukuMouseClicked

    private void cHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHAPUSActionPerformed
        int opsi = JOptionPane.showOptionDialog(this,
            "Yakin Akan Menghapus Data?"+txNIM.getText() +" ?",
            "Konfirmasi Hapus Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, null, null);
        if(opsi==JOptionPane.YES_OPTION){
            try {
                destroyData();
                lsdtpeminjaman();
                clearform();
                cHAPUS.setEnabled(false);
                cUBAH.setEnabled(false);

            } catch (SQLException ex) {
                Logger.getLogger(fPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cHAPUSActionPerformed

    private void cUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUBAHActionPerformed
        if(cUBAH.getText().equals("Ubah")){

            cUBAH.setText("Simpan");
            cKELUAR.setText("Batal");

            cTAMBAH.setEnabled(false);
            cHAPUS.setEnabled(false);
            fieldAktif(true);

            txNIM.setEditable(false);

        }else{
            try {
                updateData();
                lsdtpeminjaman();
            } catch (SQLException ex) {
                Logger.getLogger(fPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }

            cUBAH.setText("Ubah");
            cKELUAR.setText("Tutup");

            cTAMBAH.setEnabled(true);
            cUBAH.setEnabled(false);

            fieldAktif(false);
            clearform();
        }
    }//GEN-LAST:event_cUBAHActionPerformed

    private void cTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTAMBAHActionPerformed
        if(cTAMBAH.getText().equals("Tambah")){
            clearform();
            fieldAktif(true);

            cTAMBAH.setText("Simpan");
            cKELUAR.setText("Batal");
            cUBAH.setEnabled(false);
            cHAPUS.setEnabled(false);
        }else{
            try {
                storeData();
                lsdtpeminjaman();
            } catch (SQLException ex) {
                Logger.getLogger(fPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
            cTAMBAH.setText("Tambah");
            cKELUAR.setText("Keluar");
            clearform();
            fieldAktif(false);

        }
    }//GEN-LAST:event_cTAMBAHActionPerformed

    private void cTAMBAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cTAMBAHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cTAMBAHMouseClicked

    private void cKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKELUARActionPerformed
        if(cKELUAR.getText().equals("Keluar")){
            int opsi = JOptionPane.showOptionDialog(this, "Yakin Akan Keluar Aplikasi?", "Konfirmasi Keluar Aplikasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(opsi==JOptionPane.YES_OPTION){
                System.exit(0);
            }

        }else{
            cKELUAR.setText("Keluar");
            cTAMBAH.setText("Tambah");
            cUBAH.setText("Ubah");

            cUBAH.setEnabled(true);
            cUBAH.setEnabled(false);

            fieldAktif(false);
            clearform();
        }
    }//GEN-LAST:event_cKELUARActionPerformed

    private void txNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fPeminjaman().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cHAPUS;
    private javax.swing.JButton cKELUAR;
    private javax.swing.JButton cTAMBAH;
    private javax.swing.JButton cUBAH;
    private com.toedter.calendar.JDateChooser dateKEMBALI;
    private com.toedter.calendar.JDateChooser datePINJAM;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpeminjaman_buku;
    private javax.swing.JTextField txJUDUL;
    private javax.swing.JTextField txJUMLAHPEMINJAMAN;
    private javax.swing.JTextField txKODE;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNIM;
    // End of variables declaration//GEN-END:variables

    private void lsdtpeminjaman() throws SQLException {
        Connection cnn = koneksi ();
        
        DTM.getDataVector().removeAllElements();
        DTM.fireTableDataChanged();
        
        if( !cnn.isClosed()){
            PreparedStatement PS = cnn.prepareStatement("SELECT *FROM peminjaman_buku;");
            ResultSet RS = PS.executeQuery();
            while( RS.next() ){
                Object[] dtpeminjaman = new Object[7];
                dtpeminjaman[0] = RS.getString("ID");
                dtpeminjaman[1] = RS.getString("NIM");
                dtpeminjaman[2] = RS.getString("NAMA");
                dtpeminjaman[3] = RS.getString("KODE_BUKU");
                dtpeminjaman[4] = RS.getString("JUDUL_BUKU");
                dtpeminjaman[5] = RS.getString("TANGGAL_PINJAM");
                dtpeminjaman[6] = RS.getString("TANGGAL_KEMBALI");
                
                DTM.addRow(dtpeminjaman);
            }
                hitungJumlahPeminjaman();
        }
    }
    
    
    private void clearform(){
        txNIM.setText("");
        txNAMA.setText("");
        txKODE.setText("");
        txJUDUL.setText("");
        datePINJAM.setDate(null);
        dateKEMBALI.setDate(null);
    }
    
    
    private void storeData() throws SQLException {
       Connection cnn = koneksi();
       String nim = txNIM.getText();
       String nama = txNAMA.getText();
       String kode = txKODE.getText();
       String judul = txJUDUL.getText();
       
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String tglPinjam = sdf.format(datePINJAM.getDate());
       String tglKembali = sdf.format(dateKEMBALI.getDate());

       
       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("INSERT INTO peminjaman_buku (nim, nama, kode_buku, judul_buku, tanggal_pinjam, tanggal_kembali) VALUES (?, ?, ?, ?, ?, ?)");
           PS.setString(1, nim);
           PS.setString(2, nama);
           PS.setString(3, kode);
           PS.setString(4, judul);
           PS.setString(5, tglPinjam);
           PS.setString(6, tglKembali);
           
           PS.executeUpdate();
       }
    }
    
    
    private void updateData() throws SQLException {
       Connection cnn = koneksi();
       String nim = txNIM.getText();
       String nama = txNAMA.getText();
       String kode = txKODE.getText();
       String judul = txJUDUL.getText();
       
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String tglPinjam = sdf.format(datePINJAM.getDate());
       String tglKembali = sdf.format(dateKEMBALI.getDate());

       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("UPDATE peminjaman_buku SET NAMA=?,KODE_BUKU=?,JUDUL_BUKU=?, TANGGAL_PINJAM=?, TANGGAL_KEMBALI=? WHERE NIM=?;");
           PS.setString(1, nama);
           PS.setString(2, kode);
           PS.setString(3, judul);
           PS.setString(4, tglPinjam);
           PS.setString(5, tglKembali);
           PS.setString(6, nim);
           
           int rows = PS.executeUpdate();
        System.out.println("Baris yang diupdate: " + rows);
       }
    }
    
    
    private void destroyData() throws SQLException {
       Connection cnn = koneksi();
       String nim = txNIM.getText();
       
       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("DELETE FROM peminjaman_buku WHERE NIM=?;");
           PS.setString(1, nim);
           PS.executeUpdate();
           cnn.close();
       }
    }
    
    
    private void hitungJumlahPeminjaman() {
    int jumlah = tblpeminjaman_buku.getRowCount();
    txJUMLAHPEMINJAMAN.setText(String.valueOf(jumlah));
}
    
   

}
